[optimization]
preset = "maximum"

[javascript]
local_name_coalescing = false
emit_pure_annotations = true
priority = "size-first"
optimization_level = 0
cost_model = "brotli"
function_spelling = "arrow"
local_name_reserve = 48

[mangle]
identifiers = true
properties = true
exports = false
pool_strings = true
